export const LOGIN_ADMIN_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_ADMIN_SUCCESS= "LOGIN_USER_SUCCESS"
export const LOGIN_ADMIN_FAIL = "LOGIN_USER_FAIL"


export const REGISTER_RESTAURANT_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_RESTAURANT_SUCCESS= "REGISTER_USER_SUCCESS"
export const REGISTER_RESTAURANT_FAIL = "REGISTER_USER_FAIL"

export const REGISTER_DELIVERY_PERSON_REQUEST = "REGISTER_DELIVERY_PERSON_REQUEST"
export const REGISTER_DELIVERY_PERSON_SUCCESS= "REGISTER_DELIVERY_PERSON_SUCCESS"
export const REGISTER_DELIVERY_PERSON_FAIL = "REGISTER_DELIVERY_PERSON_FAIL"


export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_RESTAURANTS_REQUEST = 'FETCH_RESTAURANTS_REQUEST';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANTS_FAIL = 'FETCH_RESTAURANTS_FAIL';

export const FETCH_DELIVERY_PERSONS_REQUEST = 'FETCH_DELIVERY_PERSONS_REQUEST';
export const FETCH_DELIVERY_PERSONS_SUCCESS = 'FETCH_DELIVERY_PERSONS_SUCCESS';
export const FETCH_DELIVERY_PERSONS_FAIL = 'FETCH_DELIVERY_PERSONS_FAIL';

export const BLOCK_UNBLOCK_USER_REQUEST = 'BLOCK_UNBLOCK_USER_REQUEST';
export const BLOCK_UNBLOCK_USER_SUCCESS = 'BLOCK_UNBLOCK_USER_SUCCESS';
export const BLOCK_UNBLOCK_USER_FAIL = 'BLOCK_UNBLOCK_USER_FAIL';


export const BLOCK_UNBLOCK_RESTAURANT_REQUEST = 'BLOCK_UNBLOCK_USER_REQUEST';
export const BLOCK_UNBLOCK_RESTAURANT_SUCCESS = 'BLOCK_UNBLOCK_USER_SUCCESS';
export const BLOCK_UNBLOCK_RESTAURANT_FAIL = 'BLOCK_UNBLOCK_USER_FAIL';

export const BLOCK_UNBLOCK_DELIVERYBOY_REQUEST = 'BLOCK_UNBLOCK_USER_REQUEST';
export const BLOCK_UNBLOCK_DELIVERYBOY_SUCCESS = 'BLOCK_UNBLOCK_USER_SUCCESS';
export const BLOCK_UNBLOCK_DELIVERYBOY_FAIL = 'BLOCK_UNBLOCK_USER_FAIL';