export const ADD_CATEGORY_REQUEST='ADD_CATEGORY_REQUEST'
export const ADD_CATEGORY_SUCCESS='ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL='ADD_CATEGORY_FAIL'

export const FETCH_FOODITEMS_REQUEST='FETCH_CATEGORY_REQUEST'
export const FETCH_FOODITEMS_SUCCESS='FETCH_CATEGORY_SUCCESS'
export const FETCH_FOODITEMS_FAIL='FETCH_CATEGORY_FAIL'