export const LOGIN_RESTAURANT_REQUEST = "LOGIN_RESTAURANT_REQUEST"
export const LOGIN_RESTAURANT_SUCCESS= "LOGIN_RESTAURANT_SUCCESS"
export const LOGIN_RESTAURANT_FAIL = "LOGIN_RESTAURANT_FAIL"

export const LOGIN_RESTAURANTS_SUCCESS= "LOGIN_RESTAURANTS_SUCCESS"



export const CUISINE_ADD_REQUEST='CUISINE_ADD_REQUEST'
export const CUISINE_ADD_SUCCESS='CUISINE_ADD_SUCCESS'
export const CUISINE_ADD_FAIL='CUISINE_ADD_FAILL'


export const ADD_FOOD_ITEM_REQUEST = 'ADD_FOOD_ITEM_REQUEST';
export const ADD_FOOD_ITEM_SUCCESS = 'ADD_FOOD_ITEM_SUCCESS';
export const ADD_FOOD_ITEM_FAIL = 'ADD_FOOD_ITEM_FAIL';


export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_CUISINE_REQUEST = 'FETCH_CUISINE_REQUEST';
export const FETCH_CUISINE_SUCCESS = 'FETCH_CUISINE_SUCCESS';
export const FETCH_CUISINE_FAIL = 'FETCH_CUISINE_FAIL';

export const FETCH_FOODITEM_REQUEST='FETCH_FOODITEM_REQUEST'
export const  FETCH_FOODITEM_SUCCESS='FETCH_FOODITEM_SUCCESS'
export const FETCH_FOODITEM_FAIL ='FETCH_FOODITEM_FAIL'

export const  DELETE_FOODITEM_REQUEST='DELETE_FOODITEM_REQUEST'
export const DELETE_FOODITEM_SUCCESS='DELETE_FOODITEM_SUCCESS'
export const  DELETE_FOODITEM_FAIL='DELETE_FOODITEM_FAIL'

export const DELETE_CUISINE_REQUEST='DELETE_CUISINE_REQUEST'
export const DELETE_CUISINE_SUCCESS='DELETE_CUISINE_REQUEST'
export const DELETE_CUISINE_FAIL='DELETE_CUISINE_REQUEST'

export const DELETE_CATAGORY_REQUEST='DELETE_CATAGORY_REQUEST'
export const DELETE_CATAGORY_SUCCESS='DELETE_CATAGORY_REQUEST'
export const DELETE_CATAGORY_FAIL='DELETE_CATAGORY_REQUEST'