//USER REGISTRATION

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS= "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const OTP_USER_REQUEST ="OTP_USER_REQUEST"
export const  OTP_USER_SUCCESS="OTP_USER_SUCCESS"
export const OTP_USER_FAIL="OTP_USER_FAIL"


export const REGISTER_GOOGLE_REQUEST='REGISTER_GOOGLE_REQUEST'
export const REGISTER_GOOGLE_SUCCESS='REGISTER_GOOGLE_SUCCESS'
export const REGISTER_GOOGLE_FAIL='REGISTER_GOOGLE_FAIL'


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS= "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const LOGIN_ADMIN_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_ADMIN_SUCCESS= "LOGIN_USER_SUCCESS"
export const LOGIN_ADMIN_FAIL = "LOGIN_USER_FAIL"

export const REGISTER_RESTAURANT_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_RESTAURANT_SUCCESS= "REGISTER_USER_SUCCESS"
export const REGISTER_RESTAURANT_FAIL = "REGISTER_USER_FAIL"

export const REGISTER_DELIVERY_PERSON_REQUEST = "REGISTER_DELIVERY_PERSON_REQUEST"
export const REGISTER_DELIVERY_PERSON_SUCCESS= "REGISTER_DELIVERY_PERSON_SUCCESS"
export const REGISTER_DELIVERY_PERSON_FAIL = "REGISTER_DELIVERY_PERSON_FAIL"


///fetch

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const  FETCH_CART_SUCCESS = ' FETCH_CART_SUCCESS';
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL';



 
  


